-- begin ONLINEMARKET_ORDER
alter table ONLINEMARKET_ORDER add constraint FK_ONLINEMARKET_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references ONLINEMARKET_CUSTOMER(ID)^
alter table ONLINEMARKET_ORDER add constraint FK_ONLINEMARKET_ORDER_ON_SHIPMENT foreign key (SHIPMENT_ID) references MARKET_SHIPMENT(ID)^
create index IDX_ONLINEMARKET_ORDER_ON_CUSTOMER on ONLINEMARKET_ORDER (CUSTOMER_ID)^
create index IDX_ONLINEMARKET_ORDER_ON_SHIPMENT on ONLINEMARKET_ORDER (SHIPMENT_ID)^
-- end ONLINEMARKET_ORDER
-- begin ONLINEMARKET_CUSTOMER
alter table ONLINEMARKET_CUSTOMER add constraint FK_ONLINEMARKET_CUSTOMER_ON_ADDRESS foreign key (ADDRESS_ID) references MARKET_ADDRESS(ID)^
create index IDX_ONLINEMARKET_CUSTOMER_ON_ADDRESS on ONLINEMARKET_CUSTOMER (ADDRESS_ID)^
-- end ONLINEMARKET_CUSTOMER
-- begin DAWD
alter table dawd add constraint FK_DAWD_ON_ID foreign key (ID) references ONLINEMARKET_CUSTOMER(ID) on delete CASCADE^
-- end DAWD
-- begin DAWDD
alter table dawdd add constraint FK_DAWDD_ON_ID foreign key (ID) references ONLINEMARKET_CUSTOMER(ID) on delete CASCADE^
-- end DAWDD
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_CUSTOMER foreign key (CUSTOMER_ID) references ONLINEMARKET_CUSTOMER(ID)^
create index IDX_SEC_USER_ON_CUSTOMER on SEC_USER (CUSTOMER_ID)^
-- end SEC_USER
